version: '3'
services:
  app:
    build: .
    container_name: node-rutas
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - REDIS_URL=redis://redis01:6379
      - NEO4j_URL=neo4j://neo4j_Ges:7687
    depends_on:
      - redis
      - neo4j
    networks:
      - backend  
    command: npm start

  redis:
    image: redis
    container_name: redis01
    ports:
      - "6379:6379"
    depends_on:
      - neo4j
    networks:
      - backend

  neo4j:
    image: neo4j
    container_name: neo4j_Ges
    environment:
      - NEO4J_AUTH=none
    ports:
      - "7687:7687"
      - "7474:7474"
    networks:
      - backend

networks:
  backend:
    driver: bridge
